# Generated by Django 2.2 on 2019-04-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20190411_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Onepluse', 'Onepluse'), ('Dell', 'Dell'), ('Hp', 'Hp')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Laptop', 'Laptop')], max_length=200),
        ),
    ]
