# Generated by Django 2.2 on 2019-04-18 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0007_auto_20190412_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Dell', 'Dell'), ('Onepluse', 'Onepluse'), ('Hp', 'Hp')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_type',
            field=models.CharField(choices=[('accessories', 'accessories'), ('Electronic_product', 'Electronic_product')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Mobile', 'Mobile')], max_length=200),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_statement', models.CharField(max_length=255)),
                ('review_sentiment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
