# Generated by Django 2.2 on 2019-04-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20190419_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Onepluse', 'Onepluse'), ('Hp', 'Hp'), ('Apple', 'Apple'), ('Dell', 'Dell')], max_length=200),
        ),
    ]
