# Generated by Django 2.2 on 2019-05-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20190420_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='display_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processor_spped',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Pepsi', 'Pepsi'), ('Nandini', 'Nandini'), ('Sea_Cone', 'Sea_Cone'), ('Sunset', 'Sunset'), ('KFC', 'KFC'), ('MTR', 'MTR'), ('Nescafe', 'Nescafe'), ('Dairy_Milk', 'Dairy_Milk')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Food_Drinks', 'Food_Drinks'), ('Fruites_Vegitables', 'Fruites_Vegitables')], max_length=200),
        ),
    ]
