# Generated by Django 2.2 on 2019-05-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20190501_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('KFC', 'KFC'), ('Dairy_Milk', 'Dairy_Milk'), ('Sunset', 'Sunset'), ('Nandini', 'Nandini'), ('Pepsi', 'Pepsi'), ('Nescafe', 'Nescafe'), ('Sea_Cone', 'Sea_Cone'), ('MTR', 'MTR')], max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_type',
            field=models.CharField(choices=[('Non_veg', 'Non_veg'), ('Ready_Food', 'Ready_Food'), ('veg', 'veg'), ('Cooking', 'Cooking')], max_length=100),
        ),
    ]
